CURRENCIES = "USD, EUR, JPY, AUD, GBP, CHF, NZD, CAD"
ALL_CURRENCY_PAIRS = [
    'USD_JPY', 'USD_CHF', 'USD_CAD', 'EUR_USD', 'EUR_JPY', 'EUR_AUD',
    'EUR_GBP', 'EUR_CHF', 'EUR_NZD', 'EUR_CAD', 'AUD_USD', 'AUD_JPY',
    'AUD_CHF', 'AUD_NZD', 'AUD_CAD', 'GBP_USD', 'GBP_JPY', 'GBP_AUD',
    'GBP_CHF', 'GBP_NZD', 'GBP_CAD', 'CHF_JPY', 'NZD_USD', 'NZD_JPY',
    'NZD_CHF', 'NZD_CAD', 'CAD_JPY', 'CAD_CHF'
]

INCREMENTS = {'M5': 5, 'H1': 60, 'H4': 240}

BUY = 1
SELL = -1
NONE = 0
